### ISSUE TITLE
Remove Survey Result json shown at bottom in Test Survey

### ISSUE THREAD

**Issue by testweird123** [surveyjs/editor#362]
### Are you requesting a feature, reporting a bug or ask a question?
How to remove the "survey result : {}" json shown at the bottom of test survey tab. I would like the user to view only the test survey again button.

### Specify your

* browser: Chrome 67
* editor version: 1.0.28

**Comment by tsv2013** [comment]
You can use the following CSS rule:
```CSS
.svd_content survey-widget + div {
    display: none;
}
```
